// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/soso","parentId":"@@/global-layout","id":"2"},"3":{"path":"/app","parentId":"@@/global-layout","id":"3"},"4":{"path":"/setweb","parentId":"@@/global-layout","id":"4"},"5":{"path":"/read","parentId":"@@/global-layout","id":"5"},"6":{"path":"/welcome","parentId":"@@/global-layout","id":"6"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__soso" */'@/pages/soso.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__app__index" */'@/pages/app/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__setweb" */'@/pages/setweb.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__read__index" */'@/pages/read/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__welcome" */'@/pages/welcome.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'F:/Nodejsapp/code/src/layouts/index.tsx')),
},
  };
}
